sudo: false

cache:
  directories:
    - $HOME/.cache/pip

language: python

matrix:
  include:
    - python: '3.7'
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.5'
      env: TOXENV=py35
    - python: 'pypy3'
      env: TOXENV=pypy3
    - python: '3.7'
      env: TOXENV=py37,coverage
      dist: xenial
      sudo: true
    - python: '3.7'
      env: TOXENV=docs
      dist: xenial
      sudo: true
    - python: '3.7'
      env: TOXENV=lint
      dist: xenial
      sudo: true

install: pip install tox

script: tox
